# Generated by Django 5.2 on 2025-11-25 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_integration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="presignup",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="Cadastro Concluído"),
        ),
        migrations.AlterField(
            model_name="historicalpresignup",
            name="is_finished",
            field=models.BooleanField(default=False, verbose_name="Cadastro Concluído"),
        ),
    ]
