# Generated by Django 5.2 on 2025-11-25 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_integration", "0002_presignup_is_finished_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="presignup",
            name="request_signup_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID de Requisição de Cadastro"
            ),
        ),
    ]
