# Generated by Django 5.2 on 2025-11-25 20:44

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm_integration", "0003_presignup_request_signup_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presignup",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid7, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
