# Generated by Django 5.2 on 2025-10-14 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprofile",
            name="email",
            field=models.EmailField(
                db_index=True, max_length=254, verbose_name="E-mail"
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="email",
            field=models.EmailField(max_length=254, unique=True, verbose_name="E-mail"),
        ),
    ]
