# Generated by Django 5.2 on 2025-11-25 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_alter_historicalprofile_email_alter_profile_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalprofile",
            name="profileType",
            field=models.IntegerField(
                choices=[
                    (1, "Administrador"),
                    (2, "Desenvolvedor"),
                    (3, "Usuário do CRM"),
                ],
                default=3,
                verbose_name="Tipo de Perfil",
            ),
        ),
        migrations.AlterField(
            model_name="profile",
            name="profileType",
            field=models.IntegerField(
                choices=[
                    (1, "Administrador"),
                    (2, "Desenvolvedor"),
                    (3, "Usuário do CRM"),
                ],
                default=3,
                verbose_name="Tipo de Perfil",
            ),
        ),
    ]
